### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by yhdesai** [yhdesai/React-HTML-UI#6]

**Comment by tiger-yash** [comment]
Hello!
I would like to would one this issue, can you please assign it to me?

**Comment by yhdesai** [comment]
Hello @tiger-yash, I just changed the base to CRA so the project got migrated to typescript during that, but feel free to pick any of the other remaining issues.

**Comment by yhdesai** [comment]
Although it would be best to just wait for tomorrow to contribute to anything to this repo, I'm gonna be making a lot of breaking changes today, so PRs might face merge conflicts or entire files might just be deleted. So it would be better to contribute to this repo tomorrow @tiger-yash
